### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by siyuan126** [DESCHA1/intro-data-capstone-biodiversity#2]
**Great work**! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your **Python work** was excellent, everything worked the way it was supposed to. Please submit your code either in a jupyter notebook or py file to make it more readable. 

**Presentation:** You have correctly plot two plots in your code but I only see the first one in your presentation, why is the second one missing on the presentation? Great job calculating p values to compare the differences between species, which serve evidence to support your conclusion. Your conclusions were succinct and on point, but they are so clustered together and mixed with background or technical info, making them very hard to read. About the design of the presentation, the titles and splash page make it easy to follow, great job there.I would love to see the fonts be bigger and text displayed more balanced. 

Excellent work overall.

**Comment by DESCHA1** [comment]
Thanks for your comments: your review of my project seems eminently fair (I need to work on making better use of PowerPoint)!
